# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  dev:
    desc: "run go server"
    cmd: go run cmd/http/main.go

  compose:up:
    desc: "run all docker containers"
    cmd: docker compose up -d

  compose:down:
    desc: "stop all docker containers"
    cmd: docker compose down

  db:cli:
    desc: "access postgres db cli"
    cmd: docker exec -it postgres psql -U {{ .DB_USER }} -b {{ .DB_NAME }}

  redis:cli:
    desc: "access redis cache cli"
    cmd: docker exec -it redis redis-cli -p {{ .REDIS_PORT }} -a {{ .REDIS_PASSWORD }}

  mock:gen:
    desc: "generate mock files"
    cmd: go generate ./...

  docs:gen:
    desc: "generate swagger docs"
    cmd: swag init -g cmd/http/main.go

  docs:fmt:
    desc: "fmt swagger docs"
    cmd: swag fmt
